config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :tags

  devise_for :users
  devise_scope :user do
    get 'sign_up', to: 'devise/registrations#new'
    get 'sign_in', to: 'devise/sessions#new'
    get 'sign_out', to: 'devise/sessions#destroy'
  end

  root 'static_pages#top'

  get 'about' => 'static_pages#about'
  get 'thankyou' => 'static_pages#thankyou'

  mount Markdown::API => '/'

end

app/models/feedback.rb
class CarrierStringIO < StringIO
  def original_filename
    "image.png"
  end

  def content_type
    "image/png"
  end
end

class Feedback < ActiveRecord::Base
  belongs_to :user

  has_many :tag_feedbacks
  has_many :tags, through: :tag_feedbacks

  mount_uploader :file, FileUploader

  validates :comment, presence: true

  attr_accessor :tag_labels
  attr_accessor :file_data

  def user?(user)
    return false unless user
    user_id == user.id
  end

  def tagged?(tag)
    return false unless tag
    tag_feedbacks.find_by(tag_id: tag.id)
  end

  def add!(tag)
    tag_feedbacks.find_or_create_by!(tag_id: tag.id)
  end

  def file_data=(data)
    return false unless data && data.length > 0
    self.file = CarrierStringIO.new(Base64.decode64(data['data:image/png;base64,'.length .. -1]))
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  has_many :tag_feedbacks
  has_many :feedbacks, through: :tag_feedbacks
end

app/models/tag_feedback.rb
class TagFeedback < ActiveRecord::Base
  belongs_to :tag
  belongs_to :feedback
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true

  has_many :feedbacks
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
    devise_parameter_sanitizer.for(:account_update) << :name
  end

  def append_info_to_payload(payload)
    super
    payload[:remote_ip] = request.env['HTTP_X_FORWARDED_FOR'] || request.remote_ip
  end
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  def index
    @feedbacks = Feedback.all.order('created_at desc').page(params[:page])
  end

  def show
    @feedback = Feedback.find(params[:id])
  end

  def new
    if user_signed_in?
      @feedback = current_user.feedbacks.build
    else
      @feedback = Feedback.new
    end

    if params[:v].present? && params[:v] == 'part'
      session[:v] = 'part'
    else
      session.delete(:v)
    end

    if params[:u].present?
      @feedback.url = params[:u]
    end

    if params[:t].present?
      @feedback.tag_labels = params[:t]
    end
  end

  def create
    if user_signed_in?
      @feedback = current_user.feedbacks.build(feedback_params)
    else
      @feedback = Feedback.new(feedback_params)
    end

    if @feedback.save
      save_tags

      if session[:v].present?
        redirect_to thankyou_path
      else
        redirect_to @feedback, notice: 'Created'
      end
    else
      render :new
    end
  end

  def edit
    @feedback = Feedback.find(params[:id])

    tags = @feedback.tags.collect(&:label)
    @feedback.tag_labels = tags.join(', ')
  end

  def update
    @feedback = current_user.feedbacks.find(params[:id])
    if @feedback.update(feedback_params)
      save_tags
      redirect_to @feedback, notice: 'Updated'
    else
      render :new
    end
  end

  private

  def feedback_params
    params.require(:feedback).permit(
      :comment, :url, :tag_labels, :file, :file_cache, :remove_file, :file_data
    )
  end

  def save_tags
    tags = params[:feedback][:tag_labels].split(',')
    tags.each do |label|
      tag = Tag.find_or_create_by(label: label.strip)
      tag.save!

      @feedback.add!(tag)
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all
  end

  def show
    @tag = Tag.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_class_for(level)
    case level
    when 'success' then 'alert-success'
    when 'notice'  then 'alert-info'
    when 'alert'   then 'alert-warning'
    when 'error'   then 'alert-danger'
    end
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/feedbacks/_feedback.html.slim
= link_to feedback, class: "list-group-item list-item"
  div
    .list-group-item-text.clearfix
      p.ellipsis
        - if feedback.comment?
          = Markdown.text feedback.comment

      div
        .pull-right
          - if feedback.user.present?
            = feedback.user.name
          - else
            | Anonymous

      div
        = render feedback.tags, with_link: false

app/views/feedbacks/_form.html.slim
= form_for(feedback, class: 'form-horizontal', role: 'form') do |f|
  - if feedback.errors.any?
    .alert.alert-danger
      ul
        - feedback.errors.full_messages.each do |msg|
          li #{msg}

  .form-group
    .panel.panel-default
      .panel-body
        ul.nav.nav-tabs role="tablist"
          li.active
            a href="#write" role="tab" data-toggle="tab"
              | Write
          li
            a href="#preview" role="tab" data-toggle="tab"
              | Preview
        .tab-content
          .tab-pane.fade.in.active#write
            = f.text_area :comment, class: 'form-control', rows: 10, placeholder: 'Comment'
          .tab-pane.fade#preview
            #markdown

  .form-group class=(session[:v] ? 'sr-only' : '')
    = f.text_field :url, class: 'form-control', placeholder: 'URL'

  .form-group class=(session[:v] ? 'sr-only' : '')
    = f.text_field :tag_labels, class: 'form-control', placeholder: 'Tags'

  .form-group
    .feedback-file
      - if feedback.file?
        div
          = image_tag feedback.file
          =< f.check_box :remove_file
          | Remove this file
    = f.file_field :file
    = f.hidden_field :file_cache
    = f.hidden_field :file_data

  .button-group
    = f.submit task, class: 'btn btn-primary', data: { disable_with: 'Processing...' }
    - if session[:v] != 'part'
      = link_to 'Cancel', feedback, class: "btn btn-default"
    - else
      = link_to 'Capture screen', '#', class: "btn btn-info", id: 'partCapture'
      = link_to 'Cancel', '#', class: 'btn btn-default', id: 'partCancel'

app/views/feedbacks/edit.html.slim
h2 Edit feedback

= render 'form', feedback: @feedback, task: 'Update'

app/views/feedbacks/index.html.slim
.center
  = paginate @feedbacks

.list-group
  = render @feedbacks

.center
  = paginate @feedbacks

app/views/feedbacks/new.html.slim
h2 Send feedback

= render 'form', feedback: @feedback, task: 'Send'

app/views/feedbacks/show.html.slim
.panel.panel-default
  .panel-heading
    | User
  .panel-body
    - if @feedback.user.present?
      = @feedback.user.name
    - else
      | Anonymous

.panel.panel-default
  .panel-heading
    | Comment
  .panel-body
    - if @feedback.comment?
      = Markdown.html @feedback.comment

.panel.panel-default
  .panel-heading
    | URL
  .panel-body
    = link_to @feedback.url, @feedback.url

.panel.panel-default
  .panel-heading
    | Tags
  .panel-body
    = render @feedback.tags, with_link: true

.panel.panel-default
  .panel-heading
    | Attached file
  .panel-body.feedback-file
    = image_tag @feedback.file

.button-group
  - if @feedback.user?(current_user)
    = link_to 'Edit', edit_feedback_path(@feedback), class: 'btn btn-info'
    = link_to 'Delete', feedback_path(@feedback), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?'}

app/views/layouts/_footer.html.slim
footer
  .container
    br
    hr

    p &copy; 2014 Ikuo Terado

app/views/layouts/_header.html.slim
header.navbar.navbar-default role="navigation"
  .container
    .navbar-header
      button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to "fdbk", root_path, class: "navbar-brand", id: "logo"

    .collapse.navbar-collapse#bs-example-navbar-collapse-1

      ul.nav.navbar-nav
        li
          = link_to "About", about_path
        li
          = link_to "Feedbacks", feedbacks_path
        li
          = link_to "Tags", tags_path

      ul.nav.navbar-nav.navbar-right
        li
          .dropdown
            button.btn.btn-default.dropdown-toggle#dropdownMenuAction type="button" data-toggle="dropdown"
              | Action
              span.caret<
            ul.dropdown-menu role="menu" aria-labelledby="dropdownMenuAction"
              li role="presentation"
                = link_to "Feedback", new_feedback_path
        li
          div
            - if !user_signed_in?
              = link_to "Sign in", sign_in_path, class: "btn btn-success"
            - else
              .dropdown
                button.btn.btn-default.dropdown-toggle#dropdownMenuUser type="button" data-toggle="dropdown"
                  = current_user.name
                  span.caret<
                ul.dropdown-menu role="menu" aria-labelledby="dropdownMenuUser"
                  li role="presentation"
                    = link_to "Sign out", sign_out_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title fdbk
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    - if session[:v] != 'part'
      = render partial: 'layouts/header'

    .container
      - flash.each do |key, value|
        .alert.alert-dismissible class="#{bootstrap_class_for(key)}"
          button.close type="button" data-dismiss="alert"
            span aria-hidden="true"
              | &times;
            span.sr-only
              | Close
          = value

    .container
      = yield

    - if session[:v] != 'part'
      = render partial: 'layouts/footer'

app/views/static_pages/about.html.slim
h1 StaticPages#about
p Find me in app/views/static_pages/about.html.slim

app/views/static_pages/thankyou.html.slim
h4
  | Thank you for sending the feedback!

br

button#partCancel.btn.btn-default
  | Close

app/views/static_pages/top.html.slim
.jumbotron
  h1 Hello, world!
  p This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.
  p
    = link_to "Learn more »", about_path, class: "btn btn-primary btn-lg"

.row
  .col-md-4
    h3 Heading
    p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
  .col-md-4
    h3 Heading
    p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
  .col-md-4
    h3 Heading
    p Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.

app/views/tags/_tag.html.slim
- if with_link.present? && with_link
  = link_to tag
    span.label.label-primary.tag
      = tag.label
- else
  span
    span.label.label-primary.tag
      = tag.label

app/views/tags/index.html.slim
h2 All tags

= render @tags, with_link: true

app/views/tags/show.html.slim
h3
  = render @tag, with_link: false
br

= render @tag.feedbacks